name: Build MD Daily Scheduler APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip build-essential \
            git-core curl libssl-dev libffi-dev libsqlite3-dev \
            libjpeg-dev libfreetype6-dev libgl1-mesa-dev

          pip install --upgrade pip
          pip install buildozer cython

      - name: Build APK
        run: |
          buildozer -v android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v3
        with:
          name: md_daily_scheduler_apk
          path: bin/*.apk
