name: Build MD Daily Scheduler APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Download Android SDK
        uses: android-actions/setup-android@v2

      - name: Install Android Build Tools and Platform
        run: |
          sdkmanager "platforms;android-34" "build-tools;34.0.0"

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build APK
        run: ./gradlew assembleDebug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: md-daily-scheduler-apk
          path: app/build/outputs/apk/debug/app-debug.apk
